# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [10]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.3.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [11]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [12]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones

import numpy as np
matrix = np.full((10,10),0)
matrix[0::2,1::2]=1
matrix[1::2,::2]=1
print(matrix)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [13]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [14]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
import numpy as np
arr = np.zeros((1000, 1000), dtype=np.float64)
print(arr.nbytes, "bytes")

8000000 bytes


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [15]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [16]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a = np.arange(1, 13).reshape(4, 3)
print("Original array:\n", a)
a[[0, -1]] = a[[-1, 0]]
print("\nAfter swapping first and last rows:\n", a)



Original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After swapping first and last rows:
 [[10 11 12]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [17]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [18]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
a = np.array([[1, 2], [3, 4]])
print(a.ravel())
print(a.flatten())


[1 2 3 4]
[1 2 3 4]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [19]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [20]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
xy = np.arange(10)  # 0 to 9
print("Original array:", xy)
halves = np.array_split(xy, 2)
print("First half:", halves[0])
print("Second half:", halves[1])

Original array: [0 1 2 3 4 5 6 7 8 9]
First half: [0 1 2 3 4]
Second half: [5 6 7 8 9]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [21]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [22]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
degrees = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(degrees)
sin_values = np.sin(radians)
print("Radians: ", radians)
print("Sine values: ", sin_values)

Radians:  [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values:  [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [23]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [24]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
row = np.arange(1, 11)        
col = np.arange(1, 11).reshape(10, 1)  
matrix = col * row 
print(matrix)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [25]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [26]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
percentiles = np.percentile(data, [25, 50, 75])
print("25th, 50th, 75th percentiles:", percentiles)

25th, 50th, 75th percentiles: [3. 5. 7.]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [27]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [28]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
rolls = np.random.randint(1, 7, size=100)
prop_6s = np.mean(rolls == 6)
print("Proportion of 6s:", prop_6s)

Proportion of 6s: 0.24


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [29]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [30]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
from numpy.lib import recfunctions as rfn
data = np.array([(1, 'Alice'), (2, 'Bob')],
                dtype=[('id', 'i4'), ('name', 'U10')])
data = rfn.append_fields(data, 'height', [165, 180], usemask=False)
print(data)

[(1, 'Alice', 165) (2, 'Bob', 180)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [31]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [32]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
A = np.array([[4, 2],
              [1, 3]])
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)

Eigenvalues: [5. 2.]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [33]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [34]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
data = np.array([[1.5, 2.3, 3.7],
                 [4.1, 5.6, 6.8]])
np.savetxt("data.csv", data, delimiter=",", fmt="%.2f")
loaded_data = np.loadtxt("data.csv", delimiter=",")
print("Original data:\n", data)
print("\nLoaded data:\n", loaded_data)

Original data:
 [[1.5 2.3 3.7]
 [4.1 5.6 6.8]]

Loaded data:
 [[1.5 2.3 3.7]
 [4.1 5.6 6.8]]


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [35]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [36]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
dates = np.array(['2025-08-01', '2025-08-04', '2025-08-11', '2025-08-12'],
                 dtype='datetime64[D]')
mondays = np.sum(dates.astype('datetime64[D]').astype(int) % 7 == 0)
print("Number of Mondays:", mondays)

Number of Mondays: 0


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [37]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [38]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
arr = np.array([[1,  np.nan, 3],
                [4,  5,      np.nan],
                [7,  8,      9]], dtype=float)
col_means = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_means, inds[1])
print(arr)

[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [39]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [40]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.

date_strings = fitness['date']
parsed_dates = np.array(
    [f"{d.split('-')[2]}-{d.split('-')[1]}-{d.split('-')[0]}" for d in date_strings],
    dtype='datetime64[D]'
)

dates = parsed_dates
steps = fitness['step_count']
sleep = fitness['hours_of_sleep']
mood = fitness['mood']

months = dates.astype('datetime64[M]')
print("Monthly step count:")
for m in np.unique(months):
    print(m, steps[months == m].sum())

print("\nSleep vs mood correlation:", np.corrcoef(sleep, mood)[0, 1])


weeks = (dates - dates[0]) // 7
print("\nWeekly summary:")
for w in np.unique(weeks):
    mask = weeks == w
    print(f"Week {w+1}: steps={steps[mask].mean():.0f}, "
          f"sleep={sleep[mask].mean():.2f}, mood={mood[mask].mean():.2f}")



Monthly step count:
2017-10 79051
2017-11 103071
2017-12 89565
2018-01 10163

Sleep vs mood correlation: 0.2104166644730015

Weekly summary:
Week 1 days: steps=4684, sleep=5.57, mood=128.57
Week 2 days: steps=2662, sleep=6.29, mood=128.57
Week 3 days: steps=2863, sleep=5.57, mood=157.14
Week 4 days: steps=2400, sleep=5.86, mood=257.14
Week 5 days: steps=3554, sleep=4.57, mood=285.71
Week 6 days: steps=3876, sleep=5.29, mood=300.00
Week 7 days: steps=3310, sleep=5.57, mood=285.71
Week 8 days: steps=2668, sleep=6.00, mood=257.14
Week 9 days: steps=2929, sleep=7.00, mood=271.43
Week 10 days: steps=3742, sleep=4.14, mood=185.71
Week 11 days: steps=2654, sleep=4.43, mood=171.43
Week 12 days: steps=3001, sleep=4.43, mood=171.43
Week 13 days: steps=1189, sleep=3.29, mood=142.86
Week 14 days: steps=1023, sleep=5.00, mood=220.00


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*